local Constants = {
    PERFORMANCE_REPORT_DELAY = 30,
    NUM_COLLISION_RAYS = 100,
    MAX_FLIGHT_SPEED = 100,
    MIN_FLIGHT_SPEED = 10,
    NUM_SMALL_OBSTACLES = 100,
    NUM_MEDIUM_OBSTACLES = 50,
    NUM_LARGE_OBSTACLES = 30,
}

return Constants